const express = require('express');
const router  = express.Router();
const multer  = require('multer');
const path    = require('path');
const { requireAuth } = require('../middleware/auth');
const ctrl = require('../controllers/profileController');
const storage = multer.diskStorage({ destination:(req,file,cb)=>cb(null,path.join(__dirname,'../public/uploads')), filename:(req,file,cb)=>cb(null,`${Date.now()}-${file.originalname.replace(/\s/g,'_')}`) });
const upload = multer({ storage, limits:{fileSize:5*1024*1024} });
router.get('/',  requireAuth, ctrl.getProfile);
router.post('/', requireAuth, upload.single('avatar'), ctrl.updateProfile);
module.exports = router;
